import { useState } from 'react'
import { useAuth } from '../contexts/AuthContext'
import { useToast } from '../contexts/ToastContext'
import { supabase } from '../utils/supabase'
import {
  calculateNetSalary,
  formatCurrency,
  TAX_BANDS,
  PERSONAL_RELIEF,
  NSSF_AMOUNT,
  SHIF_RATE,
  HOUSING_LEVY_RATE
} from '../utils/calculations'
import { Calculator as CalcIcon, Info, Save, Download, Eye, EyeOff } from 'lucide-react'

export default function Calculator() {
  const { user } = useAuth()
  const { showToast } = useToast()
  const [grossSalary, setGrossSalary] = useState('')
  const [result, setResult] = useState(null)
  const [showBreakdown, setShowBreakdown] = useState(false)
  const [saving, setSaving] = useState(false)
  const [saveMessage, setSaveMessage] = useState('')

  const handleCalculate = () => {
    if (!grossSalary || parseFloat(grossSalary) <= 0) {
      showToast('Validation Error', 'Please enter a valid gross salary', 'warning')
      return
    }

    const calculation = calculateNetSalary(parseFloat(grossSalary))
    setResult(calculation)
    setShowBreakdown(false)
  }

  const handleSave = async () => {
    if (!result) return

    setSaving(true)
    setSaveMessage('')

    try {
      const currentMonth = new Date().toISOString().split('T')[0].slice(0, 7) + '-01'

      const { data, error } = await supabase
        .from('deductions')
        .upsert([
          {
            user_id: user.id,
            gross_salary: result.grossSalary,
            nssf: result.nssf,
            housing_levy: result.housingLevy,
            shif: result.shif,
            taxable_income: result.taxableIncome,
            paye: result.paye,
            personal_relief: result.personalRelief,
            total_deductions: result.totalDeductions,
            net_salary: result.netSalary,
            month: currentMonth
          }
        ], { onConflict: 'user_id,month' })

      if (error) throw error

      setSaveMessage('✓ Saved successfully!')
      setTimeout(() => setSaveMessage(''), 3000)
    } catch (error) {
      console.error('Error saving:', error)
      setSaveMessage('✗ Error saving. Try again.')
    } finally {
      setSaving(false)
    }
  }

  const handleDownload = () => {
    if (!result) return

    const payslip = `
KENYA PAYSLIP - ${new Date().toLocaleDateString('en-KE', { month: 'long', year: 'numeric' })}
================================================================

GROSS SALARY:                    ${formatCurrency(result.grossSalary)}

STATUTORY DEDUCTIONS:
------------------------------------
NSSF (Fixed):                    ${formatCurrency(result.nssf)}
Housing Levy (1.5%):             ${formatCurrency(result.housingLevy)}
SHIF (2.75%):                    ${formatCurrency(result.shif)}

TAXABLE INCOME:                  ${formatCurrency(result.taxableIncome)}

PAYE Calculation:
  Before Personal Relief:        ${formatCurrency(result.paye + result.personalRelief)}
  Personal Relief:              -${formatCurrency(result.personalRelief)}
PAYE (After Relief):             ${formatCurrency(result.paye)}

------------------------------------
TOTAL DEDUCTIONS:                ${formatCurrency(result.totalDeductions)}
====================================

NET SALARY:                      ${formatCurrency(result.netSalary)}

Deduction Rate: ${result.deductionPercentage}%

================================================================
Generated by KenyaPesa Tracker
${new Date().toLocaleString('en-KE')}
`

    const blob = new Blob([payslip], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `payslip-${new Date().toISOString().slice(0, 7)}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const getTaxBandBreakdown = () => {
    if (!result) return []

    const breakdown = []
    let previousThreshold = 0
    const taxableIncome = result.taxableIncome

    for (const band of TAX_BANDS) {
      if (taxableIncome <= previousThreshold) break

      const upperLimit = band.threshold === Infinity ? taxableIncome : Math.min(taxableIncome, band.threshold)
      const taxableInBand = upperLimit - previousThreshold
      const taxInBand = taxableInBand * band.rate

      breakdown.push({
        range: band.label,
        rate: `${(band.rate * 100)}%`,
        taxableAmount: taxableInBand,
        tax: taxInBand
      })

      previousThreshold = band.threshold
    }

    return breakdown
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div className="card">
        <div className="flex items-center space-x-3 mb-4">
          <div className="bg-blue-100 dark:bg-blue-900/30 rounded-lg p-3">
            <CalcIcon className="h-8 w-8 text-blue-600 dark:text-blue-400" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-gray-100">Salary Calculator</h2>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Calculate your net salary with accurate KRA deductions
            </p>
          </div>
        </div>

        {/* Info Box */}
        <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4 mb-6">
          <div className="flex items-start space-x-3">
            <Info className="h-5 w-5 text-blue-600 dark:text-blue-400 mt-0.5 flex-shrink-0" />
            <div className="text-sm text-blue-900 dark:text-blue-100">
              <p className="font-semibold mb-1">2024/2025 Tax Rates Applied:</p>
              <ul className="list-disc list-inside space-y-1 text-blue-800 dark:text-blue-200">
                <li>NSSF: KES 1,080 (fixed)</li>
                <li>Housing Levy: 1.5% of gross salary</li>
                <li>SHIF: 2.75% of gross salary</li>
                <li>PAYE: Progressive rates (10%-35%) with KES 2,400 personal relief</li>
              </ul>
            </div>
          </div>
        </div>

        {/* Input Section */}
        <div className="space-y-4">
          <div>
            <label className="label">
              Gross Monthly Salary (KES)
            </label>
            <input
              type="number"
              className="input text-lg"
              placeholder="100,000"
              value={grossSalary}
              onChange={(e) => setGrossSalary(e.target.value)}
              onKeyPress={(e) => e.key === 'Enter' && handleCalculate()}
            />
          </div>

          <button
            onClick={handleCalculate}
            className="w-full btn btn-primary py-3 text-lg"
          >
            Calculate Net Salary
          </button>
        </div>
      </div>

      {/* Results */}
      {result && (
        <div className="space-y-6 animate-slideIn">
          {/* Net Salary Highlight */}
          <div className="bg-gradient-to-r from-kenya-green to-green-700 rounded-xl p-8 text-white text-center">
            <p className="text-sm font-medium text-green-100 mb-2">Your Net Salary</p>
            <p className="text-5xl font-bold mb-2">{formatCurrency(result.netSalary)}</p>
            <p className="text-green-100">
              {result.deductionPercentage}% deducted from gross salary
            </p>
          </div>

          {/* Summary Cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="card">
              <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Gross Salary</p>
              <p className="text-2xl font-bold text-gray-900 dark:text-gray-100">{formatCurrency(result.grossSalary)}</p>
            </div>
            <div className="card">
              <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Total Deductions</p>
              <p className="text-2xl font-bold text-red-600 dark:text-red-400">{formatCurrency(result.totalDeductions)}</p>
            </div>
            <div className="card">
              <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Net Salary</p>
              <p className="text-2xl font-bold text-green-600 dark:text-green-400">{formatCurrency(result.netSalary)}</p>
            </div>
          </div>

          {/* Deductions Breakdown */}
          <div className="card">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-4">
              Statutory Deductions Breakdown
            </h3>

            <div className="space-y-3">
              {/* NSSF */}
              <div className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700">
                <div>
                  <p className="font-medium text-gray-900 dark:text-gray-100">NSSF</p>
                  <p className="text-xs text-gray-600 dark:text-gray-400">Fixed monthly contribution</p>
                </div>
                <p className="text-lg font-semibold text-gray-900 dark:text-gray-100">{formatCurrency(result.nssf)}</p>
              </div>

              {/* Housing Levy */}
              <div className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700">
                <div>
                  <p className="font-medium text-gray-900 dark:text-gray-100">Housing Levy</p>
                  <p className="text-xs text-gray-600 dark:text-gray-400">1.5% of gross salary</p>
                </div>
                <p className="text-lg font-semibold text-gray-900 dark:text-gray-100">{formatCurrency(result.housingLevy)}</p>
              </div>

              {/* SHIF */}
              <div className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700">
                <div>
                  <p className="font-medium text-gray-900 dark:text-gray-100">SHIF (Social Health Insurance)</p>
                  <p className="text-xs text-gray-600 dark:text-gray-400">2.75% of gross salary</p>
                </div>
                <p className="text-lg font-semibold text-gray-900 dark:text-gray-100">{formatCurrency(result.shif)}</p>
              </div>

              {/* Taxable Income */}
              <div className="flex items-center justify-between p-3 bg-blue-50 dark:bg-blue-900/30 rounded-lg border border-blue-200 dark:border-blue-800">
                <div>
                  <p className="font-medium text-gray-900 dark:text-gray-100">Taxable Income</p>
                  <p className="text-xs text-gray-600 dark:text-gray-400">After NSSF, Housing Levy & SHIF</p>
                </div>
                <p className="text-lg font-semibold text-blue-600 dark:text-blue-400">{formatCurrency(result.taxableIncome)}</p>
              </div>

              {/* PAYE */}
              <div className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700">
                <div className="flex-1">
                  <div className="flex items-center justify-between mb-1">
                    <p className="font-medium text-gray-900 dark:text-gray-100">PAYE (Income Tax)</p>
                    <button
                      onClick={() => setShowBreakdown(!showBreakdown)}
                      className="text-xs text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 flex items-center"
                    >
                      {showBreakdown ? <EyeOff className="h-3 w-3 mr-1" /> : <Eye className="h-3 w-3 mr-1" />}
                      {showBreakdown ? 'Hide' : 'Show'} breakdown
                    </button>
                  </div>
                  <p className="text-xs text-gray-600 dark:text-gray-400">
                    Tax before relief: {formatCurrency(result.paye + result.personalRelief)}
                    <br />
                    Personal relief: -{formatCurrency(result.personalRelief)}
                  </p>
                </div>
                <p className="text-lg font-semibold text-gray-900 dark:text-gray-100 ml-4">{formatCurrency(result.paye)}</p>
              </div>

              {/* PAYE Band Breakdown */}
              {showBreakdown && (
                <div className="ml-4 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-200 dark:border-blue-800 space-y-2">
                  <p className="text-sm font-semibold text-gray-900 dark:text-gray-100 mb-3">PAYE Tax Band Breakdown:</p>
                  {getTaxBandBreakdown().map((band, index) => (
                    <div key={index} className="flex items-center justify-between text-sm">
                      <div>
                        <span className="text-gray-700 dark:text-gray-300">KES {band.range}</span>
                        <span className="text-gray-500 dark:text-gray-400 ml-2">@ {band.rate}</span>
                      </div>
                      <div className="text-right">
                        <p className="text-gray-600 dark:text-gray-400">On {formatCurrency(band.taxableAmount)}</p>
                        <p className="font-semibold text-gray-900 dark:text-gray-100">{formatCurrency(band.tax)}</p>
                      </div>
                    </div>
                  ))}
                  <div className="pt-2 border-t border-blue-300 dark:border-blue-700 flex justify-between font-semibold text-gray-900 dark:text-gray-100">
                    <span>Total PAYE (before relief):</span>
                    <span>{formatCurrency(result.paye + result.personalRelief)}</span>
                  </div>
                  <div className="flex justify-between text-green-700 dark:text-green-400">
                    <span>Less: Personal Relief</span>
                    <span>-{formatCurrency(result.personalRelief)}</span>
                  </div>
                  <div className="flex justify-between font-bold text-lg text-gray-900 dark:text-gray-100">
                    <span>PAYE Payable:</span>
                    <span>{formatCurrency(result.paye)}</span>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Action Buttons */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <button
              onClick={handleSave}
              disabled={saving}
              className="btn btn-primary py-3 flex items-center justify-center"
            >
              {saving ? (
                <>
                  <span className="spinner mr-2"></span>
                  Saving...
                </>
              ) : (
                <>
                  <Save className="h-5 w-5 mr-2" />
                  Save to Records
                </>
              )}
            </button>

            <button
              onClick={handleDownload}
              className="btn btn-secondary py-3 flex items-center justify-center"
            >
              <Download className="h-5 w-5 mr-2" />
              Download Payslip
            </button>
          </div>

          {saveMessage && (
            <div className={`text-center p-3 rounded-lg ${
              saveMessage.includes('✓')
                ? 'bg-green-50 dark:bg-green-900/30 text-green-800 dark:text-green-400'
                : 'bg-red-50 dark:bg-red-900/30 text-red-800 dark:text-red-400'
            }`}>
              {saveMessage}
            </div>
          )}
        </div>
      )}

      {/* Tax Rate Reference */}
      <div className="card">
        <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-4">
          KRA Tax Rates Reference (2024/2025)
        </h3>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200 dark:border-gray-700">
                <th className="text-left py-2 px-4 text-gray-900 dark:text-gray-100">Monthly Income (KES)</th>
                <th className="text-right py-2 px-4 text-gray-900 dark:text-gray-100">Tax Rate</th>
              </tr>
            </thead>
            <tbody>
              {TAX_BANDS.map((band, index) => (
                <tr key={index} className="border-b border-gray-100 dark:border-gray-800">
                  <td className="py-2 px-4 text-gray-700 dark:text-gray-300">
                    {band.label}
                  </td>
                  <td className="text-right py-2 px-4 font-semibold text-gray-900 dark:text-gray-100">
                    {(band.rate * 100)}%
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <p className="text-xs text-gray-600 dark:text-gray-400 mt-4">
          * Personal relief of KES 2,400 per month is automatically applied to PAYE
        </p>
      </div>
    </div>
  )
}